### ISSUE TITLE
Pass 'MachineDominator Tree Constructor' is not initialized.

### ISSUE THREAD

**Issue by YuKill** [vandersonmr/GEOS#2]
When GEOS is trying to compile the code with a given optimization sequence, it fails to find a Pass called MachineDominatorTreePass. The linker doesn't seem to be the error. Initializing this specific Pass also did not solve the problem.

**Comment by vandersonmr** [comment]
The problem was reported on the llvm mail list. The thread can be followed by the link: http://permalink.gmane.org/gmane.comp.compilers.llvm.devel/91950

**Comment by vandersonmr** [comment]
Patch: https://github.com/vandersonmr/GEOS/pull/4
