### ISSUE TITLE
Estimation is yielding 0 values.

### ISSUE THREAD

**Issue by YuKill** [vandersonmr/GEOS#6]
When GEOS tries to estimate the performance after applying some optimization sequences, it returns ZERO, sometimes.

**Comment by vandersonmr** [comment]
If this problem also happens in the master branch (2.0), please commit in booths.

**Comment by YuKill** [comment]
It seems like when applying optimizations, it changes the name (or simply creates new BasicBlocks) of almost every single BasicBlock. When testing with polybench (2mm), the transformations wouldn't leave almost no BasicBlock intact. It sums up to roughly 0.5% with their names and frequency left.

**Comment by YuKill** [comment]
What if, instead of storing each BasicBlock frequency inside a unordered map, we stored it as MetaData of the BasicBlock? This way, when it is copied, the MetaData also is (we already do this when we handle the branch frequency).

**Comment by vandersonmr** [comment]
I don't think we need to store any BB frequency at all. It's possible to calculate all BB frequencies just with the branch frequencies. So, I suggest we could recalculate for ALL BB, no matter if it has or not a frequency, when ProfileModule::repairProfiling() is called. Something similar is already being done by it.
