### ISSUE TITLE
We need an objective way to measure how well we are holding the execution frequency

### ISSUE THREAD

**Issue by vandersonmr** [vandersonmr/GEOS#8]
We have discussed a lot about how badly GEOS is losing execution frequency information, but we don't have an objective way to measure it. Therefore, I think we should have a code/script which runs some tests and returns a numeric value measuring the efficiency of GEOS on holding this information.

**Comment by vandersonmr** [comment]
Maybe, we can use the PGOInstrumentation from LLVM to get the execution frequency from JIT. A commit this week added support for MST instrumentation: http://reviews.llvm.org/rL255132

**Comment by YuKill** [comment]
I see... Your update already gets all the information we want though. I think it is not necessary, I see no problems in doing it.
